# Legacy Hyprland config bind.
# Use this only if your setup still uses hyprland.conf.

bind = $mainMod, N, exec, /home/karel/Documents/Github/HyprInk/build/hyprink --toggle --config /home/karel/Documents/Github/HyprInk/Project.conf
